apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-job
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  template:
    spec:
      containers:
      - name: liquibase-job
        image: liquibase:v1
        command: [
          "liquibase",
          "update",
          "--changeLogFile=changelog.yaml",
          "--url=jdbc:postgresql://host.docker.internal:32768/liquibase",
          "--username=postgres",
          "--password=postgres"
        ]
      restartPolicy: Never
  backoffLimit: 0